#! /bin/bash

# Fail fast
set -o errexit

echo
echo "Installing bundler"
echo
gem install bundler
echo

gemfiles="Gemfile Gemfile-downgraded-hashie"

for gemfile in $gemfiles; do
  echo
  echo "Testing with $gemfile"
  echo
  bundle install --gemfile $gemfile
  bundle exec rake spec
done
